[package]
name = "kennel-club"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.6"
itertools = "0.14.0"
rand = "0.9.2"
serde = { version = "1.0.219", features = ["derive"] }
termion = "4.0.5"
