# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

[[repos]]
repo = "builtin"
hooks = [
    { id = "trailing-whitespace" },
    { id = "end-of-file-fixer" },
    { id = "check-added-large-files" },
]

[[repos]]
repo = "local"
hooks = [
    { id = "cargo-fmt", name = "cargo fmt --all --check", entry = "cargo fmt --all --check", language = "system", pass_filenames = false, always_run = true, require_serial = true },
    { id = "cargo-check", name = "cargo check", entry = "cargo check", language = "system", pass_filenames = false, always_run = true, require_serial = true },
    { id = "cargo-clippy", name = "cargo clippy", entry = "cargo clippy", language = "system", pass_filenames = false, always_run = true, require_serial = true, env = { RUSTFLAGS = "-Dwarnings" } },
    { id = "cargo-test", name = "cargo test", entry = "cargo test -- --skip test_kennel", language = "system", pass_filenames = false, always_run = true, require_serial = true },
    { id = "check-metadata-schema", name = "check-jsonschema data/metadata.json", entry = "check-jsonschema --schemafile metadata_schema.json", language = "python", additional_dependencies = ["check-jsonschema==0.38.2"], files = "^data/metadata\\.json$" },
]
