name: Deploy metadata changes

on:
  push:
    branches:
      - main
    paths:
      - 'data/*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize ssh
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST_NAME }} > ~/.ssh/known_hosts

      - name: Restart server
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST_NAME }} "./alts-alt/entrypoint.sh"

